### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by mdevey91** [ilanpatao/autotrader-api#2]
When I called autotrader's API from code I got the following error:
`Failed to load https://www.autotrader.com/rest/searchresults/sunset/base?zip=84057&startYear=1981&numRecords=100000&sortBy=relevance&firstRecord=0&endYear=2019&modelCodeList=&makeCodeList=FORD&searchRadius=1000: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.`
I looks like the API is restricted. How did you get around this?

**Comment by ilanpatao** [comment]
I updated the source of the project to accomodate the latest API changes (the endpoint schema has changed over time).

If you're using my script (PHP) you should not encounter CORS issues; however if you are using AJAX/JQuery calls (GET/POST) you'll need to use a CORS Proxy by prepending the proxy URL to your endpoint.

https://cors-anywhere.herokuapp.com/ is a free to use CORS Proxy service; modify the endpoint by prepending it to the URL

Example:

`https://cors-anywhere.herokuapp.com/https://www.autotrader.com/rest/searchresults/base?zip=84057&makeCodeList=NISSAN&modelCodeList=MAX&startYear=1981&endYear=2019&searchRadius=10000&sellerTypes=p&maxPrice=20000&sortBy=derivedpriceASC&numRecords=20000&firstRecord=0`

Note: I've updated the endpoint in the example above to reflect the latest changes in the structure.
